server {
    listen 80;
    server_name lms.gezytech.web.id;

    location /.well-known/acme-challenge/ {
        root /home/pgun/nginx-acme;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name lms.gezytech.web.id;

    ssl_certificate /home/pgun/nginx-ssl/gezytech.crt;
    ssl_certificate_key /home/pgun/nginx-ssl/gezytech.key;

    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
